// Code generated by protoc-gen-go. DO NOT EDIT.
// source: golos.proto

/*
Package proto is a generated protocol buffer package.

based on https://github.com/Appscrunch/Multy-back/

It is generated from these files:
	golos.proto

It has these top-level messages:
	OkErrResponse
	AccountCheckRequest
	AccountCheckResponse
	Accounts
	Balance
	GetBalancesResponse
	AccountCreateRequest
	BalancesChangedMessage
	GetTrackedAddressesResponse
	SendTransactionResponse
	Block
	HeadInfo
	Empty
	TransactionJSON
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type OkErrResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *OkErrResponse) Reset()                    { *m = OkErrResponse{} }
func (m *OkErrResponse) String() string            { return proto1.CompactTextString(m) }
func (*OkErrResponse) ProtoMessage()               {}
func (*OkErrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OkErrResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *OkErrResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AccountCheckRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *AccountCheckRequest) Reset()                    { *m = AccountCheckRequest{} }
func (m *AccountCheckRequest) String() string            { return proto1.CompactTextString(m) }
func (*AccountCheckRequest) ProtoMessage()               {}
func (*AccountCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountCheckRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AccountCheckResponse struct {
	Exist bool   `protobuf:"varint,1,opt,name=exist" json:"exist,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *AccountCheckResponse) Reset()                    { *m = AccountCheckResponse{} }
func (m *AccountCheckResponse) String() string            { return proto1.CompactTextString(m) }
func (*AccountCheckResponse) ProtoMessage()               {}
func (*AccountCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountCheckResponse) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

func (m *AccountCheckResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Accounts struct {
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
}

func (m *Accounts) Reset()                    { *m = Accounts{} }
func (m *Accounts) String() string            { return proto1.CompactTextString(m) }
func (*Accounts) ProtoMessage()               {}
func (*Accounts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Accounts) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type Balance struct {
	Name              string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Balance           string `protobuf:"bytes,2,opt,name=balance" json:"balance,omitempty"`
	SavingsBalance    string `protobuf:"bytes,3,opt,name=savings_balance,json=savingsBalance" json:"savings_balance,omitempty"`
	SbdBalance        string `protobuf:"bytes,4,opt,name=sbd_balance,json=sbdBalance" json:"sbd_balance,omitempty"`
	SavingsSbdBalance string `protobuf:"bytes,5,opt,name=savings_sbd_balance,json=savingsSbdBalance" json:"savings_sbd_balance,omitempty"`
	VestingBalance    string `protobuf:"bytes,6,opt,name=vesting_balance,json=vestingBalance" json:"vesting_balance,omitempty"`
}

func (m *Balance) Reset()                    { *m = Balance{} }
func (m *Balance) String() string            { return proto1.CompactTextString(m) }
func (*Balance) ProtoMessage()               {}
func (*Balance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Balance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Balance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Balance) GetSavingsBalance() string {
	if m != nil {
		return m.SavingsBalance
	}
	return ""
}

func (m *Balance) GetSbdBalance() string {
	if m != nil {
		return m.SbdBalance
	}
	return ""
}

func (m *Balance) GetSavingsSbdBalance() string {
	if m != nil {
		return m.SavingsSbdBalance
	}
	return ""
}

func (m *Balance) GetVestingBalance() string {
	if m != nil {
		return m.VestingBalance
	}
	return ""
}

type GetBalancesResponse struct {
	Balances []*Balance `protobuf:"bytes,1,rep,name=balances" json:"balances,omitempty"`
	Error    string     `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetBalancesResponse) Reset()                    { *m = GetBalancesResponse{} }
func (m *GetBalancesResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetBalancesResponse) ProtoMessage()               {}
func (*GetBalancesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetBalancesResponse) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *GetBalancesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AccountCreateRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Owner   string `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	Active  string `protobuf:"bytes,3,opt,name=active" json:"active,omitempty"`
	Posting string `protobuf:"bytes,4,opt,name=posting" json:"posting,omitempty"`
	Memo    string `protobuf:"bytes,5,opt,name=memo" json:"memo,omitempty"`
	Fee     string `protobuf:"bytes,6,opt,name=fee" json:"fee,omitempty"`
}

func (m *AccountCreateRequest) Reset()                    { *m = AccountCreateRequest{} }
func (m *AccountCreateRequest) String() string            { return proto1.CompactTextString(m) }
func (*AccountCreateRequest) ProtoMessage()               {}
func (*AccountCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AccountCreateRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountCreateRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AccountCreateRequest) GetActive() string {
	if m != nil {
		return m.Active
	}
	return ""
}

func (m *AccountCreateRequest) GetPosting() string {
	if m != nil {
		return m.Posting
	}
	return ""
}

func (m *AccountCreateRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *AccountCreateRequest) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

type BalancesChangedMessage struct {
	Balances []*Balance `protobuf:"bytes,1,rep,name=balances" json:"balances,omitempty"`
}

func (m *BalancesChangedMessage) Reset()                    { *m = BalancesChangedMessage{} }
func (m *BalancesChangedMessage) String() string            { return proto1.CompactTextString(m) }
func (*BalancesChangedMessage) ProtoMessage()               {}
func (*BalancesChangedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BalancesChangedMessage) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

type GetTrackedAddressesResponse struct {
	Accounts []string `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
	Error    string   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetTrackedAddressesResponse) Reset()                    { *m = GetTrackedAddressesResponse{} }
func (m *GetTrackedAddressesResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetTrackedAddressesResponse) ProtoMessage()               {}
func (*GetTrackedAddressesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetTrackedAddressesResponse) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *GetTrackedAddressesResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SendTransactionResponse struct {
	Ok       bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Response string `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
}

func (m *SendTransactionResponse) Reset()                    { *m = SendTransactionResponse{} }
func (m *SendTransactionResponse) String() string            { return proto1.CompactTextString(m) }
func (*SendTransactionResponse) ProtoMessage()               {}
func (*SendTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SendTransactionResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SendTransactionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SendTransactionResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type Block struct {
	Height       uint32               `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Time         int64                `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Transactions []*Block_Transaction `protobuf:"bytes,3,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto1.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Block) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Block) GetTransactions() []*Block_Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Block_Transaction struct {
	RefBlockNum    uint32   `protobuf:"varint,1,opt,name=ref_block_num,json=refBlockNum" json:"ref_block_num,omitempty"`
	RefBlockPrefix uint32   `protobuf:"varint,2,opt,name=ref_block_prefix,json=refBlockPrefix" json:"ref_block_prefix,omitempty"`
	Expiration     int64    `protobuf:"varint,3,opt,name=expiration" json:"expiration,omitempty"`
	Operations     string   `protobuf:"bytes,4,opt,name=operations" json:"operations,omitempty"`
	Signatures     []string `protobuf:"bytes,6,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *Block_Transaction) Reset()                    { *m = Block_Transaction{} }
func (m *Block_Transaction) String() string            { return proto1.CompactTextString(m) }
func (*Block_Transaction) ProtoMessage()               {}
func (*Block_Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

func (m *Block_Transaction) GetRefBlockNum() uint32 {
	if m != nil {
		return m.RefBlockNum
	}
	return 0
}

func (m *Block_Transaction) GetRefBlockPrefix() uint32 {
	if m != nil {
		return m.RefBlockPrefix
	}
	return 0
}

func (m *Block_Transaction) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *Block_Transaction) GetOperations() string {
	if m != nil {
		return m.Operations
	}
	return ""
}

func (m *Block_Transaction) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type HeadInfo struct {
	Height uint32 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *HeadInfo) Reset()                    { *m = HeadInfo{} }
func (m *HeadInfo) String() string            { return proto1.CompactTextString(m) }
func (*HeadInfo) ProtoMessage()               {}
func (*HeadInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *HeadInfo) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HeadInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type TransactionJSON struct {
	Json string `protobuf:"bytes,1,opt,name=json" json:"json,omitempty"`
}

func (m *TransactionJSON) Reset()                    { *m = TransactionJSON{} }
func (m *TransactionJSON) String() string            { return proto1.CompactTextString(m) }
func (*TransactionJSON) ProtoMessage()               {}
func (*TransactionJSON) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TransactionJSON) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto1.RegisterType((*OkErrResponse)(nil), "proto.OkErrResponse")
	proto1.RegisterType((*AccountCheckRequest)(nil), "proto.AccountCheckRequest")
	proto1.RegisterType((*AccountCheckResponse)(nil), "proto.AccountCheckResponse")
	proto1.RegisterType((*Accounts)(nil), "proto.Accounts")
	proto1.RegisterType((*Balance)(nil), "proto.Balance")
	proto1.RegisterType((*GetBalancesResponse)(nil), "proto.GetBalancesResponse")
	proto1.RegisterType((*AccountCreateRequest)(nil), "proto.AccountCreateRequest")
	proto1.RegisterType((*BalancesChangedMessage)(nil), "proto.BalancesChangedMessage")
	proto1.RegisterType((*GetTrackedAddressesResponse)(nil), "proto.GetTrackedAddressesResponse")
	proto1.RegisterType((*SendTransactionResponse)(nil), "proto.SendTransactionResponse")
	proto1.RegisterType((*Block)(nil), "proto.Block")
	proto1.RegisterType((*Block_Transaction)(nil), "proto.Block.Transaction")
	proto1.RegisterType((*HeadInfo)(nil), "proto.HeadInfo")
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*TransactionJSON)(nil), "proto.TransactionJSON")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeCommunications service

type NodeCommunicationsClient interface {
	EventGetHeadInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeadInfo, error)
	EventAccountCheck(ctx context.Context, in *AccountCheckRequest, opts ...grpc.CallOption) (*AccountCheckResponse, error)
	EventAccountCreate(ctx context.Context, in *AccountCreateRequest, opts ...grpc.CallOption) (*OkErrResponse, error)
	EventGetBalances(ctx context.Context, in *Accounts, opts ...grpc.CallOption) (*GetBalancesResponse, error)
	EventTrackAddresses(ctx context.Context, in *Accounts, opts ...grpc.CallOption) (*OkErrResponse, error)
	EventGetTrackedAddresses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Accounts, error)
	EventSendTransactionJSON(ctx context.Context, in *TransactionJSON, opts ...grpc.CallOption) (*SendTransactionResponse, error)
	BalanceChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NodeCommunications_BalanceChangedClient, error)
	NewBlock(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NodeCommunications_NewBlockClient, error)
}

type nodeCommunicationsClient struct {
	cc *grpc.ClientConn
}

func NewNodeCommunicationsClient(cc *grpc.ClientConn) NodeCommunicationsClient {
	return &nodeCommunicationsClient{cc}
}

func (c *nodeCommunicationsClient) EventGetHeadInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeadInfo, error) {
	out := new(HeadInfo)
	err := grpc.Invoke(ctx, "/proto.NodeCommunications/EventGetHeadInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) EventAccountCheck(ctx context.Context, in *AccountCheckRequest, opts ...grpc.CallOption) (*AccountCheckResponse, error) {
	out := new(AccountCheckResponse)
	err := grpc.Invoke(ctx, "/proto.NodeCommunications/EventAccountCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) EventAccountCreate(ctx context.Context, in *AccountCreateRequest, opts ...grpc.CallOption) (*OkErrResponse, error) {
	out := new(OkErrResponse)
	err := grpc.Invoke(ctx, "/proto.NodeCommunications/EventAccountCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) EventGetBalances(ctx context.Context, in *Accounts, opts ...grpc.CallOption) (*GetBalancesResponse, error) {
	out := new(GetBalancesResponse)
	err := grpc.Invoke(ctx, "/proto.NodeCommunications/EventGetBalances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) EventTrackAddresses(ctx context.Context, in *Accounts, opts ...grpc.CallOption) (*OkErrResponse, error) {
	out := new(OkErrResponse)
	err := grpc.Invoke(ctx, "/proto.NodeCommunications/EventTrackAddresses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) EventGetTrackedAddresses(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Accounts, error) {
	out := new(Accounts)
	err := grpc.Invoke(ctx, "/proto.NodeCommunications/EventGetTrackedAddresses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) EventSendTransactionJSON(ctx context.Context, in *TransactionJSON, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := grpc.Invoke(ctx, "/proto.NodeCommunications/EventSendTransactionJSON", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommunicationsClient) BalanceChanged(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NodeCommunications_BalanceChangedClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_NodeCommunications_serviceDesc.Streams[0], c.cc, "/proto.NodeCommunications/BalanceChanged", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeCommunicationsBalanceChangedClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeCommunications_BalanceChangedClient interface {
	Recv() (*Balance, error)
	grpc.ClientStream
}

type nodeCommunicationsBalanceChangedClient struct {
	grpc.ClientStream
}

func (x *nodeCommunicationsBalanceChangedClient) Recv() (*Balance, error) {
	m := new(Balance)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeCommunicationsClient) NewBlock(ctx context.Context, in *Empty, opts ...grpc.CallOption) (NodeCommunications_NewBlockClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_NodeCommunications_serviceDesc.Streams[1], c.cc, "/proto.NodeCommunications/NewBlock", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeCommunicationsNewBlockClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeCommunications_NewBlockClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type nodeCommunicationsNewBlockClient struct {
	grpc.ClientStream
}

func (x *nodeCommunicationsNewBlockClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for NodeCommunications service

type NodeCommunicationsServer interface {
	EventGetHeadInfo(context.Context, *Empty) (*HeadInfo, error)
	EventAccountCheck(context.Context, *AccountCheckRequest) (*AccountCheckResponse, error)
	EventAccountCreate(context.Context, *AccountCreateRequest) (*OkErrResponse, error)
	EventGetBalances(context.Context, *Accounts) (*GetBalancesResponse, error)
	EventTrackAddresses(context.Context, *Accounts) (*OkErrResponse, error)
	EventGetTrackedAddresses(context.Context, *Empty) (*Accounts, error)
	EventSendTransactionJSON(context.Context, *TransactionJSON) (*SendTransactionResponse, error)
	BalanceChanged(*Empty, NodeCommunications_BalanceChangedServer) error
	NewBlock(*Empty, NodeCommunications_NewBlockServer) error
}

func RegisterNodeCommunicationsServer(s *grpc.Server, srv NodeCommunicationsServer) {
	s.RegisterService(&_NodeCommunications_serviceDesc, srv)
}

func _NodeCommunications_EventGetHeadInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).EventGetHeadInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeCommunications/EventGetHeadInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).EventGetHeadInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_EventAccountCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).EventAccountCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeCommunications/EventAccountCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).EventAccountCheck(ctx, req.(*AccountCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_EventAccountCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).EventAccountCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeCommunications/EventAccountCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).EventAccountCreate(ctx, req.(*AccountCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_EventGetBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accounts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).EventGetBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeCommunications/EventGetBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).EventGetBalances(ctx, req.(*Accounts))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_EventTrackAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accounts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).EventTrackAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeCommunications/EventTrackAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).EventTrackAddresses(ctx, req.(*Accounts))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_EventGetTrackedAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).EventGetTrackedAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeCommunications/EventGetTrackedAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).EventGetTrackedAddresses(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_EventSendTransactionJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionJSON)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommunicationsServer).EventSendTransactionJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NodeCommunications/EventSendTransactionJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommunicationsServer).EventSendTransactionJSON(ctx, req.(*TransactionJSON))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommunications_BalanceChanged_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeCommunicationsServer).BalanceChanged(m, &nodeCommunicationsBalanceChangedServer{stream})
}

type NodeCommunications_BalanceChangedServer interface {
	Send(*Balance) error
	grpc.ServerStream
}

type nodeCommunicationsBalanceChangedServer struct {
	grpc.ServerStream
}

func (x *nodeCommunicationsBalanceChangedServer) Send(m *Balance) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeCommunications_NewBlock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeCommunicationsServer).NewBlock(m, &nodeCommunicationsNewBlockServer{stream})
}

type NodeCommunications_NewBlockServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type nodeCommunicationsNewBlockServer struct {
	grpc.ServerStream
}

func (x *nodeCommunicationsNewBlockServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

var _NodeCommunications_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NodeCommunications",
	HandlerType: (*NodeCommunicationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EventGetHeadInfo",
			Handler:    _NodeCommunications_EventGetHeadInfo_Handler,
		},
		{
			MethodName: "EventAccountCheck",
			Handler:    _NodeCommunications_EventAccountCheck_Handler,
		},
		{
			MethodName: "EventAccountCreate",
			Handler:    _NodeCommunications_EventAccountCreate_Handler,
		},
		{
			MethodName: "EventGetBalances",
			Handler:    _NodeCommunications_EventGetBalances_Handler,
		},
		{
			MethodName: "EventTrackAddresses",
			Handler:    _NodeCommunications_EventTrackAddresses_Handler,
		},
		{
			MethodName: "EventGetTrackedAddresses",
			Handler:    _NodeCommunications_EventGetTrackedAddresses_Handler,
		},
		{
			MethodName: "EventSendTransactionJSON",
			Handler:    _NodeCommunications_EventSendTransactionJSON_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BalanceChanged",
			Handler:       _NodeCommunications_BalanceChanged_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "NewBlock",
			Handler:       _NodeCommunications_NewBlock_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "golos.proto",
}

func init() { proto1.RegisterFile("golos.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xeb, 0x44,
	0x10, 0x96, 0x93, 0xe6, 0xe7, 0x4c, 0x9a, 0xa4, 0x67, 0x53, 0x15, 0xcb, 0x47, 0x3a, 0x44, 0x96,
	0xd0, 0x09, 0x5c, 0x44, 0xa5, 0x88, 0x0b, 0xa4, 0x4a, 0xa8, 0x2d, 0x55, 0x00, 0x41, 0x8a, 0xdc,
	0x4a, 0x5c, 0x70, 0x51, 0x39, 0xf6, 0x24, 0x31, 0xa9, 0x77, 0xc3, 0xae, 0x93, 0x96, 0x97, 0xe1,
	0x15, 0x78, 0x00, 0x5e, 0x80, 0x67, 0xe0, 0x69, 0xd0, 0xae, 0x67, 0x1d, 0x27, 0x27, 0xb9, 0xe8,
	0x55, 0xf6, 0x9b, 0xf9, 0xf6, 0xdb, 0x99, 0x6f, 0x3d, 0x1b, 0x68, 0xcd, 0xc4, 0x93, 0x50, 0xc3,
	0xa5, 0x14, 0x99, 0x60, 0x35, 0xf3, 0xe3, 0x7f, 0x0d, 0xed, 0xbb, 0xc5, 0xad, 0x94, 0x01, 0xaa,
	0xa5, 0xe0, 0x0a, 0x59, 0x07, 0x2a, 0x62, 0xe1, 0x3a, 0x7d, 0x67, 0xd0, 0x0c, 0x2a, 0x62, 0xc1,
	0x4e, 0xa1, 0x86, 0x52, 0x0a, 0xe9, 0x56, 0xfa, 0xce, 0xe0, 0x4d, 0x90, 0x03, 0xff, 0x73, 0xe8,
	0x5d, 0x45, 0x91, 0x58, 0xf1, 0xec, 0x66, 0x8e, 0xd1, 0x22, 0xc0, 0x3f, 0x56, 0xa8, 0x32, 0xc6,
	0xe0, 0x88, 0x87, 0x29, 0x9a, 0xed, 0x6f, 0x02, 0xb3, 0xf6, 0xaf, 0xe1, 0x74, 0x9b, 0x4a, 0x07,
	0x69, 0xe1, 0x97, 0x44, 0x65, 0x74, 0x56, 0x0e, 0x0e, 0x1c, 0xd7, 0x87, 0x26, 0x69, 0x28, 0xcd,
	0xd0, 0xba, 0xca, 0x75, 0xfa, 0x55, 0xcd, 0x30, 0xc0, 0xff, 0xcf, 0x81, 0xc6, 0x75, 0xf8, 0x14,
	0xf2, 0x08, 0xf7, 0x55, 0xc1, 0x5c, 0x68, 0x4c, 0xf2, 0x34, 0x29, 0x5b, 0xc8, 0x3e, 0x40, 0x57,
	0x85, 0xeb, 0x84, 0xcf, 0xd4, 0xa3, 0x65, 0x54, 0x0d, 0xa3, 0x43, 0x61, 0x2b, 0xfb, 0x29, 0xb4,
	0xd4, 0x24, 0x2e, 0x48, 0x47, 0x86, 0x04, 0x6a, 0x12, 0x5b, 0xc2, 0x10, 0x7a, 0x56, 0xa9, 0x4c,
	0xac, 0x19, 0xe2, 0x5b, 0x4a, 0xdd, 0x6f, 0xf8, 0x1f, 0xa0, 0xbb, 0x46, 0x95, 0x25, 0x7c, 0x56,
	0x70, 0xeb, 0xf9, 0xc9, 0x14, 0x26, 0xa2, 0xff, 0x2b, 0xf4, 0x46, 0x98, 0x11, 0x52, 0x85, 0x83,
	0x5f, 0x40, 0x93, 0xf6, 0xe5, 0x66, 0xb4, 0x2e, 0x3a, 0xf9, 0xe5, 0x0e, 0x89, 0x1a, 0x14, 0xf9,
	0x03, 0xbe, 0xfe, 0xe5, 0x6c, 0x2e, 0x47, 0x62, 0x98, 0xa1, 0xbd, 0x48, 0x17, 0x1a, 0x61, 0x1e,
	0x27, 0x17, 0x2d, 0xd4, 0x42, 0xe2, 0x99, 0x63, 0x21, 0x64, 0x00, 0x3b, 0x83, 0x7a, 0x18, 0x65,
	0xc9, 0xda, 0x7a, 0x47, 0x48, 0xeb, 0x2c, 0x85, 0xe9, 0x85, 0xfc, 0xb2, 0x50, 0x5f, 0x52, 0x8a,
	0xa9, 0x20, 0x77, 0xcc, 0x9a, 0x9d, 0x40, 0x75, 0x8a, 0xd6, 0x04, 0xbd, 0xf4, 0xbf, 0x83, 0x33,
	0xdb, 0xf6, 0xcd, 0x3c, 0xe4, 0x33, 0x8c, 0x7f, 0x46, 0xa5, 0xc2, 0xd9, 0xab, 0x9a, 0xf7, 0xef,
	0xe0, 0xdd, 0x08, 0xb3, 0x07, 0x19, 0x46, 0x0b, 0x8c, 0xaf, 0xe2, 0x58, 0xa2, 0x52, 0x25, 0x1f,
	0x3d, 0x68, 0x52, 0x77, 0xf6, 0xa3, 0x2a, 0xf0, 0x01, 0xdf, 0x7e, 0x83, 0x4f, 0xee, 0x91, 0xc7,
	0x0f, 0x32, 0xe4, 0x4a, 0x77, 0x2a, 0xf8, 0xeb, 0xe6, 0x47, 0x1f, 0x29, 0x69, 0x07, 0x39, 0x56,
	0x60, 0xff, 0xef, 0x0a, 0xd4, 0xae, 0x9f, 0x44, 0xb4, 0xd0, 0xae, 0xce, 0x31, 0x99, 0xcd, 0xf3,
	0x4b, 0x68, 0x07, 0x84, 0xb4, 0x77, 0x59, 0x92, 0xe6, 0x5f, 0x72, 0x35, 0x30, 0x6b, 0x76, 0x09,
	0xc7, 0xd9, 0xa6, 0x1c, 0xe5, 0x56, 0x8d, 0x27, 0xae, 0xf5, 0x44, 0xeb, 0x0d, 0xcb, 0xf5, 0x6e,
	0xb1, 0xbd, 0x7f, 0x1c, 0x68, 0x95, 0xb2, 0xcc, 0x87, 0xb6, 0xc4, 0xe9, 0xe3, 0x44, 0x6f, 0x7b,
	0xe4, 0xab, 0x94, 0x0a, 0x68, 0x49, 0x9c, 0x1a, 0xa9, 0xf1, 0x2a, 0x65, 0x03, 0x38, 0xd9, 0x70,
	0x96, 0x12, 0xa7, 0xc9, 0x8b, 0xa9, 0xa8, 0x1d, 0x74, 0x2c, 0xed, 0x17, 0x13, 0x65, 0xef, 0x01,
	0xf0, 0x65, 0x99, 0xc8, 0x50, 0x6b, 0x9b, 0x7e, 0xab, 0x41, 0x29, 0xa2, 0xf3, 0x62, 0x89, 0x39,
	0x50, 0x76, 0xb0, 0x36, 0x11, 0x9d, 0x57, 0xc9, 0x8c, 0x87, 0xd9, 0x4a, 0xa2, 0x72, 0xeb, 0xe6,
	0x8a, 0x4a, 0x11, 0xff, 0x02, 0x9a, 0xdf, 0x63, 0x18, 0xff, 0xc0, 0xa7, 0xe2, 0xa0, 0x67, 0x1d,
	0xa8, 0x24, 0x31, 0x5d, 0x42, 0x25, 0x89, 0xfd, 0x06, 0xd4, 0x6e, 0xd3, 0x65, 0xf6, 0xa7, 0xff,
	0x19, 0x74, 0x4b, 0x9d, 0xff, 0x78, 0x7f, 0x37, 0xd6, 0xfe, 0xfe, 0xae, 0x04, 0xb7, 0x0f, 0x88,
	0x5e, 0x5f, 0xfc, 0x7b, 0x04, 0x6c, 0x2c, 0x62, 0xbc, 0x11, 0x69, 0xba, 0xe2, 0x49, 0x44, 0xa5,
	0x7d, 0x09, 0x27, 0xb7, 0x6b, 0xe4, 0xd9, 0x08, 0xb3, 0xa2, 0x84, 0x63, 0x32, 0xdd, 0xe8, 0x7b,
	0x5d, 0x42, 0x45, 0xfa, 0x27, 0x78, 0x6b, 0xb6, 0x94, 0x5f, 0x45, 0xe6, 0x11, 0x6b, 0xcf, 0xab,
	0xea, 0xbd, 0xdb, 0x9b, 0xa3, 0xef, 0x6d, 0x04, 0x6c, 0x4b, 0xcd, 0x8c, 0x31, 0xdb, 0xdd, 0x52,
	0x1e, 0x6e, 0xef, 0x94, 0x92, 0xdb, 0x0f, 0xff, 0xb7, 0x9b, 0x4e, 0xec, 0xc8, 0xb1, 0xee, 0xb6,
	0x8c, 0xf2, 0x6c, 0x99, 0xfb, 0x9e, 0xa3, 0x4b, 0xe8, 0x19, 0x01, 0x33, 0x67, 0xc5, 0x94, 0x7d,
	0xac, 0xb1, 0xff, 0xf8, 0x6f, 0xc0, 0xb5, 0xc7, 0xef, 0x0e, 0xea, 0x01, 0x43, 0x8b, 0x7f, 0x84,
	0x80, 0xb6, 0xee, 0x8c, 0xa4, 0xb9, 0xca, 0x33, 0x22, 0xef, 0xc4, 0xbd, 0xf7, 0x14, 0x3f, 0x34,
	0xc6, 0xe7, 0xd0, 0xa1, 0x06, 0xe9, 0xdd, 0xd9, 0x29, 0x62, 0xe7, 0xb1, 0x39, 0x77, 0xd8, 0x00,
	0x9a, 0x63, 0x7c, 0xce, 0x07, 0x77, 0x9b, 0x7b, 0x5c, 0x1e, 0xc2, 0x73, 0x67, 0x52, 0x37, 0xf0,
	0xab, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x55, 0x92, 0x07, 0x0d, 0x90, 0x07, 0x00, 0x00,
}
